on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: vmpods.azurecr.io
        username: ${{ secrets.acr_vmpods_username }}
        password: ${{ secrets.acr_vmpods_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/result" -f  "result/Dockerfile" -t vmpods.azurecr.io/zia:${{ github.sha }} --label dockerfile-path=result/Dockerfile
        docker push vmpods.azurecr.io/zia:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_zia_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep ingress-nginx | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace ingress-nginx`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: ingress-nginx
        container-registry-url: vmpods.azurecr.io
        container-registry-username: ${{ secrets.acr_vmpods_username }}
        container-registry-password: ${{ secrets.acr_vmpods_password }}
        secret-name: ziadockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: ingress-nginx
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
          manifests/ingress-1.yml
        images: |
          vmpods.azurecr.io/zia:${{ github.sha }}
        imagepullsecrets: |
          ziadockerauth
